# Use this to debug any slowness or problems like that
# setopt XTRACE VERBOSE

# Include other configuration
source ~/.aliases

# Disable flow control to allow ^s to work as expected
stty -ixon

# Use vim style editing
bindkey -v

# Define the editor for some commands
export EDITOR="nvim"

# Configure the history file location and sizes
HISTFILE=~/.histfile
HISTSIZE=500000
SAVEHIST=500000
setopt inc_append_history
setopt share_history
setopt histignorealldups

# Fixes a problem where git diff with color doesn't show colors
export LESS=-R 

# Automatically change to directory if you just type directory name
setopt autocd
